# ?????? ?? ??
server:
  port: 80


spring:
  # MySQL ?? ??
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306
    username: root
    password: admin
  # JPA ??
  jpa:
    hibernate:
      ddl-auto: create # ?????? ??? ??
    properties:
      hibernate:
        show_sql: true # ???? ?? ?? ??
        format_sql: true # ???? ???? ??? ???? ?? ???
    database-platform: org.hibernate.dialect.MySQL5Dialect
